config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'
  resources :users, only: [:new, :create, :show, :destroy]

  resources :admins
  resources :chefs
  resources :servers
  resources :menus
  resources :orders

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
    has_many :orders
    has_many :parties, through: :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :menu
  belongs_to :party
  belongs_to :user
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :orders
  has_many :menus, through: :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :menus, through: :orders
  has_many :parties, through: :orders


  validates :username, presence: true
  validates :email, presence:true, uniqueness: true
  validates :empl_type, inclusion: {in: ["Manager", "Chef", "Server"]}
has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @greeting = "Logged in Manager"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
    @greeting = "Logged in as Chef"
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  #before_action :authenticate

  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      redirect_to request.referer
    end
  end

  def show
    @menus
  end

#---
#both edit and update work together , you need both
  def edit
   @menu = Menu.find(params[:id])
 end

 def update
    @menu = Menu.find(params[:id])
    @menu.update(menu_params)
    redirect_to menus_path
  end
#---
  def destroy
   @menu = Menu.find(params[:id])
   @menu.destroy
   redirect_to menus_path
 end

  private

  def menu_params
    params.require(:menu).permit(:name, :cuisine, :price)
  end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #before_action :authenticate

  def index
    @orders = Order.all
    @menus = Menu.all
    @parties = Party.all
  end


  # def show
  #   @order = Order.find(params[:id])
  # end

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(order_params)
    if @order.save
      redirect_to orders_path
    else
      redirect_to request.referer
    end
  end

  private

  def order_params
    params.require(:order).permit(:menu_id, :party_id, :user_id)
  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index
    @greeting = "Logged in as Server"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password]) && user.empl_type == "Chef"
        session[:current_user_id] = user.id
        redirect_to chefs_path
      elsif user && user.authenticate(params[:password]) && user.empl_type == "Server"
        session[:current_user_id] = user.id
        redirect_to servers_path
      elsif user && user.authenticate(params[:password]) && user.empl_type == "Manager"
        session[:current_user_id] = user.id
        redirect_to admins_path
      end
  end


  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]
  def new
    @user = User.new
  end

#---
  def create
      @user = User.new(user_params)
      if @user.save
        session[:current_user_id] = @user.id
        if @user.empl_type == "Manager"
          redirect_to admins_path
        elsif @user.empl_type == "Server"
          redirect_to servers_path
        else
          redirect_to chefs_path
        end
      end
    end

    def show
      @user = User.find(params[:id])
      if @user.empl_type == "Manager"
        redirect_to admins_path
      elsif @user.empl_type == "Server"
        redirect_to servers_path
      else
        redirect_to chefs_path
      end
    end
#--
  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email, :empl_type)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<!-- #manager's page -->
<!-- create, edit and remove menu item -->


<%= @greeting %>
<br>
<%= link_to "Go to Menu", menus_path, method: :get %>
<!-- point to my view using "link_to"  -->
<br>
<%= link_to "Add a New item", new_menu_path, method: :get %>

app/views/chefs/index.html.erb
<%= @greeting %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>RestaurantApp</title>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <img src="http://icons.iconarchive.com/icons/graphicloads/polygon/256/restaurant-icon.png" class="logo">
    <div class="login">
      <% if session[:current_user_id] %>
      <h1>Welcome Back</h1>
      <%= link_to "#{User.find(session[:current_user_id]).username}", user_path(session[:current_user_id]) %> ||
      <%= link_to "Logout", sessions_path, method: :delete %>
      <% else %>
      <p>Already A Memeber</p>
      <% #TODO what's a form_tag for %>
      <%= form_tag(sessions_path) do%>
      <%= label_tag :username %>:
      <%= text_field_tag :username %>
      <br>
      <%= label_tag :password %>:
      <%= password_field_tag :password %>
      <br><br>
      <%= submit_tag "Login"%>
      <% end %>
      <% end %>
    </div>
<%= yield %>

</body>
</html>

app/views/menus/_item.html.erb
  <li>
    <%= menu.name %><span>  |  </span>
    <%= menu.cuisine %><span>  |  $</span>
    <%= menu.price %><span> |  </span>
    <%= link_to "Edit", edit_menu_path(menu.id)%>
    <%= link_to "Delete", menu_path(menu.id), method: :delete%>
  </li>

app/views/menus/edit.html.erb
<div class="form">
<h1>Add a Menu Item</h1>
 <%= form_for @menu do |f| %>
 <%= f.label :name %><br>
 <%= f.text_field :name %><br>
 <%= f.label :cuisine %><br>
 <%= f.text_field :cuisine %><br>
 <%= f.label :price %><br>
 <%= f.text_field :price%><br>
 <%= f.submit "Edit Item" %><br>
 <% end %>
</div>

app/views/menus/index.html.erb
<div class="menu">
  <h3>Menu items below</h3>
    <!-- <%= Menu.all.each do |menu| %> -->
    <%= render partial: 'item', locals: {menu: menu} %>
  <!-- <% end %> -->
</div>
<%= link_to "New Menu Item", new_menu_path%>

app/views/menus/new.html.erb
<div class="form">
<h1>Add a Menu Item</h1>
 <%= form_for @menu do |f| %>
 <%= f.label :name %><br>
 <%= f.text_field :name %><br>
 <%= f.label :cuisine %><br>
 <%= f.text_field :cuisine %><br>
 <%= f.label :price %><br>
 <%= f.text_field :price%><br>
 <%= f.submit "Create Item" %><br>
 <% end %>
</div>

app/views/orders/edit.html.erb
<div class="form">
<h1>Add a Menu Item</h1>
 <%= form_for @menu do |f| %>
 <%= f.label :name %><br>
 <%= f.text_field :name %><br>
 <%= f.label :cuisine %><br>
 <%= f.text_field :cuisine %><br>
 <%= f.label :price %><br>
 <%= f.text_field :price%><br>
 <%= f.submit "Edit Item" %><br>
 <% end %>
</div>

app/views/orders/index.html.erb
<div class="orders">
 <h2>List of Orders</h2>
 <% @parties.each do |party| %>
   <div><%= party.table_num %></div>
   <% party.menus.each do |menu| %>
     <li><%= menu.name %> <%= menu.price %></li>
   <% end %>
 <% end %>


</div>
 <%= link_to "Add a new order?", new_order_path %>

app/views/orders/new.html.erb
<div class="form">
<h1>Add an order </h1>

  <%= form_for @order do |f| %>

  <%= select("order", "party_id", Party.all.collect {|p| [ p.table_num, p.guests, p.id ] }, {prompt: 'Select Party'}) %>

  <br>

  <%= select("order", "menu_id", Menu.all.collect {|p| [ p.name, p.price, p.id ] }, {prompt: 'Select Menu Item'}) %>

  <br>
  <%= f.hidden_field :user_id, :value => session[:current_user_id] %>

  <%= f.submit "Add order"%><br>
  <% end %>
  </div>
<%= link_to "See all Orders", orders_path%>

app/views/servers/index.html.erb
<!-- #server's page -->
<!-- create  order for parties -->


<%= @greeting %><br>
<%= link_to "See my Orders", orders_path, method: :get %><br>
<%= link_to "Add a New order", new_order_path, method: :get %>

app/views/users/new.html.erb
<div class="form">
  <h1>Please Sign Up</h1>
  <%= form_for @user do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password%><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.label :employee_Type %><br>
  <%= f.select(:empl_type, ["Manager", "Server", "Chef"]) %><br>
  <%= f.submit "Sign Up" %><br>
  <% end %>
</div>

app/views/welcome/index.html.erb
Hello World